
  CREATE TABLE "SRPMS_PROJECT_UPDATE" 
   (	"ID" NUMBER(20,0) NOT NULL ENABLE, 
	"UPDATE_NUMBER" NVARCHAR2(50), 
	"DEPT_ID" NUMBER(20,0), 
	"PROJECT_ID" NUMBER(20,0), 
	"PROJECT_CODE" NVARCHAR2(200), 
	"PROJECT_NAME" NVARCHAR2(200), 
	"PROJECT_TYPE" NVARCHAR2(10), 
	"LEAD_PERSON_NAME" NVARCHAR2(64), 
	"FILE_ID" NUMBER(20,0), 
	"FILE_NAME" NVARCHAR2(200), 
	"FILE_URL" NVARCHAR2(200), 
	"UPDATE_TYPE" NVARCHAR2(20), 
	"UPDATE_REASON" NVARCHAR2(2000), 
	"UPDATE_STATE" NVARCHAR2(20), 
	"CREATE_TIME" DATE, 
	"CREATE_BY" NVARCHAR2(255), 
	"UPDATE_TIME" DATE, 
	"UPDATE_BY" NVARCHAR2(255), 
	"BUD_NUM" NVARCHAR2(50), 
	"PROJECT_FLAG" VARCHAR2(1 BYTE), 
	"UPDATE_VALUE" NVARCHAR2(1000), 
	"DEL_FLAG" VARCHAR2(1 BYTE), 
	"OLD_VALUE" NVARCHAR2(1000), 
	"NEW_VALUE" NVARCHAR2(1000), 
	 CONSTRAINT "PK_SRPMS_PRO_UPDATE_1" PRIMARY KEY ("ID")) ;

   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."ID" IS '项目变更ID';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."UPDATE_NUMBER" IS '变更单号';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."DEPT_ID" IS '单位ID';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."PROJECT_ID" IS '项目ID';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."PROJECT_CODE" IS '项目编号';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."PROJECT_NAME" IS '项目名称';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."PROJECT_TYPE" IS '项目类型';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."LEAD_PERSON_NAME" IS '项目负责人';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."FILE_ID" IS '批示文件ID';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."FILE_NAME" IS '批示文件名';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."FILE_URL" IS '批示文件URL';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."UPDATE_TYPE" IS '变更类型';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."UPDATE_REASON" IS '变更原因';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."UPDATE_STATE" IS '变更状态';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."CREATE_BY" IS '创建人';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."UPDATE_TIME" IS '更新时间';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."UPDATE_BY" IS '更新人';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."BUD_NUM" IS '预算书编号';
   COMMENT ON COLUMN "SRPMS_PROJECT_UPDATE"."PROJECT_FLAG" IS '项目标识(区分国家级与横纵项项目)';
   COMMENT ON TABLE "SRPMS_PROJECT_UPDATE"  IS '项目变更记录表';